---
name: Tree-Simple-View
version: 0.16
author:
  - 'stevan little, E<lt>stevan@iinteractive.comE<gt>'
abstract: A set of classes for viewing Tree::Simple hierarchies
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Throwable: 0.1
  Scalar::Util: 1.18
  Tree::Simple: 1.07
build_requires:
  Test::Exception: 0.15
  Test::LongString: 0
  Test::More: 0.47
provides:
  Tree::Simple::View:
    file: lib/Tree/Simple/View.pm
    version: 0.16
  Tree::Simple::View::ASCII:
    file: lib/Tree/Simple/View/ASCII.pm
    version: 0.01
  Tree::Simple::View::DHTML:
    file: lib/Tree/Simple/View/DHTML.pm
    version: 0.13
  Tree::Simple::View::Exceptions:
    file: lib/Tree/Simple/View/Exceptions.pm
    version: 0.01
  Tree::Simple::View::HTML:
    file: lib/Tree/Simple/View/HTML.pm
    version: 0.12
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
